package model

import (
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/emirate/rag-tui/ui"
)

// AnimTickMsg advances the rabbit animation by one frame.
type AnimTickMsg struct{}

// animTickCmd schedules the next animation frame (100 ms, matching the original JS).
func animTickCmd() tea.Cmd {
	return tea.Tick(100*time.Millisecond, func(_ time.Time) tea.Msg {
		return AnimTickMsg{}
	})
}

// ragtagLogo is the ASCII word-art shown beside the rabbit on startup.
// Generated with pyfiglet "standard" font — g descenders properly aligned.
const ragtagLogo = "                 _              \n" +
	" _ __ __ _  __ _| |_ __ _  __ _ \n" +
	"| '__/ _` |/ _` | __/ _` |/ _` |\n" +
	"| | | (_| | (_| | || (_| | (_| |\n" +
	"|_|  \\__,_|\\__, |\\__\\__,_|\\__, |\n" +
	"           |___/          |___/ "

// viewSplash renders the animated rabbit above the ragtag wordmark on startup.
func (m AppModel) viewSplash() string {
	frame := rabbitFrames[m.animFrame]
	frameLines := strings.Split(frame, "\n")
	// Split produces a trailing empty element from the final \n; drop it.
	if len(frameLines) > 0 && frameLines[len(frameLines)-1] == "" {
		frameLines = frameLines[:len(frameLines)-1]
	}

	h := m.viewportHeight()

	logoLines := strings.Split(ragtagLogo, "\n")
	logoHeight := len(logoLines)

	// How many rabbit lines fit above the wordmark (wordmark always shown in full).
	rabbitAvail := h - logoHeight - 1 // -1 for blank separator
	if rabbitAvail < 0 {
		rabbitAvail = 0
	}

	// Trim rabbit frame from the top — keeps the body/feet visible.
	if len(frameLines) > rabbitAvail {
		frameLines = frameLines[len(frameLines)-rabbitAvail:]
	}

	rabbitStyle := lipgloss.NewStyle().Foreground(ui.ColorDim)
	logoStyle := lipgloss.NewStyle().Foreground(ui.ColorCyan).Bold(true)

	logoBlock := logoStyle.Render(ragtagLogo)
	wordmarkBlock := logoBlock

	var block string
	if rabbitAvail > 0 {
		rabbitBlock := rabbitStyle.Render(strings.Join(frameLines, "\n"))
		block = lipgloss.JoinVertical(lipgloss.Center, rabbitBlock, "", wordmarkBlock)
	} else {
		block = wordmarkBlock
	}

	return lipgloss.NewStyle().
		Width(m.width).
		Height(h).
		Align(lipgloss.Center, lipgloss.Center).
		Render(block)
}

// rabbitFrames contains the 33 animation frames extracted from rabbit_anim.js.
var rabbitFrames = []string{
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                   jBMGE8EqXJ                     \n                 FMEr.    .,7NU                   \n                BN            BO                  \n               :B              B                  \n                BJ Ji       v .B                  \n                 BBB.       LBBi                  \n                  B,        .ZB                   \n                 :OuU       ZJB                   \n                 :BB:       7XB,                  \n                 :BB:       :BPv                  \n                 :MB.       ,B7Y                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                   ..i.,::.                       \n                 iBBBM17P5BM7                     \n               .BBi,       r0B                    \n               BB            PB                   \n               B              B                   \n               BJ  Y.      .r7B                   \n               .B5BE        iB,                   \n                 7B        :.B7                   \n                 ,8iS      NqBB                   \n                 iEMi      rJBB                   \n                 :MB,       BBB.                  \n                 :G1r       BBG:                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                 ,LBGMjMXE7                       \n                kBBBr   .LMBr                     \n              .BB:         :Br                    \n              BP            :B                    \n              B              B                    \n              Mu  ::       :BB                    \n              .BUjB:        BP                    \n                iBZ       ::LB                    \n                 Ljk.     :BNB:                   \n                 Y5B:      BvBO                   \n                 UYuu      B:MB                   \n                 JJ2v      FXBB                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                 i5NNkFkZE.                       \n               vMBBBr  .:5S0                      \n              8B ,         uB                     \n             ,BN            MF                    \n             rM             UB                    \n             .B   .,       1Bj                    \n              :BU,B7       .B:                    \n                YBO       Y.SB                    \n                 B.i      LLGBi                   \n                 B,B      rZ:BB                   \n                 B.B.     .B:UB                   \n                 ;5O:      MGUB                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                 iFB8PkN8L                        \n               qBBBB:  .::SL                      \n             .BG :         UO                     \n             uB             B:                    \n             XU             NL                    \n             rB   .        BB:                    \n              PBi.B.       .B,                    \n               .5BY       F 0B                    \n                 B,r      MrBB:                   \n                 B:B      YNLBB                   \n                 B.B,      B.8B                   \n                 G:B.      MSqB                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                    . .                           \n               ,5XBBZO8BU7                        \n              ;0BB5,    .7Mr                      \n             2M           .Bi                     \n            :BB            :B                     \n            SN             rB                     \n            iB,            BU                     \n             vBU iB        iB                     \n              .1MB0      .B BB                    \n                 Bvv      B.BB.                   \n                 B.B      XiBv1                   \n                 B B      iXM;B                   \n                 B.B       BB B                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                    ,                             \n               rGBBB58BBL.                        \n             UBXBB0     LPL                       \n            :Br           qq                      \n            BB7            B                      \n            Bi            .B                      \n            B;            :B:                     \n            .BN. ..        ,B                     \n              SMNBr      OS.BU                    \n                 B Y     ,B,BB                    \n                 B B,     B BB7                   \n                 B Br     7YB7B                   \n                 B.BL     :BB,8                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                 .,7ii:                           \n              rS1BMjiuFF5i                        \n            :NNFBMJ     .BU                       \n           .BX            B,                      \n           UBB,           GL                      \n           BP:            qu                      \n           EP             vB                      \n            BJ   .       : SZ                     \n             iq5PB       BL2BY                    \n                uB.B     :BiBB                    \n                .M.B7     B,NBi                   \n                .B.Bu     BiBYX                   \n                 B:BP     uqB B                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                . :,:,.                           \n             i0SMBBF1XBB7                         \n           .GX.vB5     .8B                        \n           BO, ,.        0B                       \n          iB8k            B                       \n          FXu             B                       \n          :B              BL                      \n           MB7             BJ                     \n            iGMN5BL     ,B BB                     \n               .iBvS     B:MPB                    \n                :1rB.    YujiB.                   \n                7U7BN    iB:Xkr                   \n                :XiMB     2XE:S                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n              i.,:i7:.                            \n            iBBNMBij1XBF                          \n          r25: j7,     rZ                         \n         iBB   .        :B                        \n          B B:           Bi                       \n         :B.i            B;                       \n          Br             :B:                      \n          .BGi            ,BY                     \n            YEM2ZB      PL BB                     \n                Mqi7     B BOS                    \n                B.NB.    1Fq:B.                   \n                B MBJ    :BU:NP                   \n                ur2kG     BN. B                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n            7Ui777ULY                             \n           uBBr2BBrjqBX                           \n        YU8Z. rq7.    XB                          \n       iBBk , ,        NE                         \n        .B YB           B                         \n        iq:B.           BJ                        \n         M              .G0                       \n         ,0Y     ,     :  BN                      \n           FMuELBB     iB.FBJ                     \n                Bi7     rB:PB:                    \n                B:BB     BiGiB                    \n                B.8Bi    FFB NZ                   \n                B BLY     P8  B                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n         iUi,:v727vi:                             \n         BBBMrLBBriu8B.                           \n     .iiLBY  :Pr     vB:                          \n     BBBB.   i        :B                          \n       rS :B.          B                          \n       O,:B:           BM                         \n       uN              1SF:                       \n        UMi      .i    i 5Bi                      \n         ,SMPS5qB0i    BJiBBr                     \n               5r:     .B.Z,B:                    \n               B:BBi    rP5,rB                    \n               M:N,B.    Bk2 B7                   \n               Lrvrkv    rB; :5                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n    vBkjX777N5uuq2Yi                              \n    .MPNB0i:.:5Z.:rUB5                            \n      :7B:  JBU:     SM                           \n ,BBN0Z    rJ         B                           \n iBGJPB  :B           B                           \n      B .B:          .Bq.                         \n      Br             BY.8L                        \n      .5U        .r   i iBB                       \n        7qNuMjGM0Uj   YBLMUB                      \n              :B i     LNEi2B                     \n              iq:BBr    B.B BN                    \n               B B B:   JOG: Bi                   \n               B B LY    Gk  7X                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n       .B8N:                                      \n        UNqBBEENNNBBu.                            \n        ,BY :.     7UBq                           \n  iB88GkF.       :u   B7                          \n  ,BPUMq      ;jBB7   ,B                          \n      8B      0L,      B                          \n      15  rBB         JB7                         \n      1B .Bv         .B:B8                        \n       BO:            7  MB.                      \n        rBN5k55jUuN   7B kBB                      \n          .::iiBrFL    BqrvFB                     \n               B.BBU   :B,E qB                    \n               B.B:Br   B,B  BL                   \n               M:M LL   5GO  Fr                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n           i:                                     \n          ;BJB...:,.                              \n          ;BLGBPqq0N8Y                            \n    ;BkqOOBr:        vX,                          \n    UMr5B.             Zi                         \n      iBi           ;  iB                         \n      :B         iBB8. .B                         \n      iB     .. LMU    BB                         \n      .B: .LqBr       iBvYi                       \n       LBi:r          .   B7                      \n        rBBvrrv:rrY    0 u,BY                     \n          .Lr7uBG0B    B M:.B.                    \n               uL:BB   ErLU S8                    \n               uuvL0Y  rSXJ  B                    \n               ;NYr,B  rBB   B,                   \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n              .LjqGqS5r                           \n           .LqBEr...:LXBN                         \n        ,,UMBBU7r       NB                        \n     UZUJSv .B2EU.       UB                       \n     iBF8B,               B:                      \n        S2         ,rNMu  B:                      \n        iB.   i7:  LP;.  iB                       \n         2B7,Y5r       rLkPB                      \n          rBBF: ... iEBEr  8B                     \n             7U7BFBj :  72.FBJ                    \n                B BB    :B:E B                    \n                B BB,   ,B,B B                    \n                B BJY   :j.7 B                    \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                .i52F21i;                         \n             iN0Ej:::::JPBB.                      \n            qBJ           LBY                     \n           08              .Bv                    \n        :vYJ    rX 57       ,B                    \n       0BSFY;  :B7ZG         B:                   \n        riBB    vvL    ,;    B:                   \n           Bi ,77i  LX10L  :OL                    \n            B8B7::       vS8B                     \n             .JvuBPBSN1kNk, Gq                    \n                :N:B      M BB                    \n                7UjB.    :M:BB                    \n                J7JB.    :S:YM                    \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                    .:,::i::,                     \n                 :XBBBBMPkPMBBGX.                 \n               .OBv            PBS                \n              iBv               .8B               \n             .BL                  Bq              \n             MN    rk B   7Z.B     B              \n             B:    01 B,  2N B     B              \n             uB    vB,B   7B2B    7B              \n              B5    21:    :r.   :B,              \n              .BM20Yirr  .rYr70vMB:               \n                 0BMBN5UYSZMZZBS;                 \n                 :OiB::i;,:,10k7                  \n                 1J:B       LU;M                  \n                 1Y.N       YL.q                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                       iJUUk0Pq27.                \n                     UBBq7.....7MBq               \n                    BM.           SGk             \n                   XS               ZM            \n                  .B        S. ,     B7           \n                  7M        rB,jF    iJ85         \n                   B   .2:   .SSZ   LkYXB         \n                   rBr  :1u2;  GYY ,BZ            \n                    BS5Ui,, ,  .:UMBL             \n                   UZ v7i1JU7B5BY7,               \n                   BB:B      B.M.                 \n                   BB.B.    LB,0:                 \n                   Nr X.    7B.G,                 \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                    i:            \n                             .,,.,:BFB            \n                           .vqEMUqB:ZB            \n                         iYi        .7BBJkBB      \n                        :B.            UBjXB      \n                        8u .S.          BU        \n                        B:  SBBL        iB        \n                        rB    ,X: r,    ,B        \n                        GBq       jBMi  BU        \n                      iO             :rBG         \n                     .B.:  : i5YYYjk0BOi          \n                     Br B72F  .BuB2::             \n                    YB  B:j1  BBY8.               \n                    BO  B:0: 1qiLB.               \n                   .B   UkB  B.7vB                \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                       ri.        \n                            r00qENEqF2UYBU        \n                          .BBi.. ...:riBB         \n                          B1   7:      :P2qSj:    \n                         :B    iBBv      OBBBG    \n                          B      .v.i    PU       \n                         ;Bi        0Br  k5       \n                        NBSN         :O. B:       \n                       OB              .EB        \n                      BM.Y,B  YPY5Uu52PMr         \n                     2B :B:B   kkjBi:i.           \n                    ,B  2i:B  5BBi2               \n                    ZG  i8rZ .B BjL               \n                    B    BM; 8Y BUL               \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                              r55jLi27:iULUBi     \n                            PBPL:rBZ::NkZPqB,     \n                           kB     ;Bq  .F0U.      \n                           B        7B    q5NBB:  \n                           B          ;L  BXSUB:  \n                          ;B.          B8 Gv      \n                        iE7jB           i B:      \n                       rB:  .  i        :Bk       \n                      YB,Z,GY .SUX77YiJBBi        \n                     iB. B,B.   :SB7Y;r:          \n                    .Br  B B  iBB.B               \n                    BX   B B .BYB.B               \n                   :B    YGB 77,N.B               \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                             ,:i,....             \n                           NNBku0B0GMBM5          \n                          BP     LBv.iBB          \n                         BY        S:  YBNFU      \n                         B           vJ BBB1      \n                        .Bi           BYBi        \n                       LEr.            XB         \n                      :B7  7    .     LB.         \n                     iB BiNv   .Gu22MBj.          \n                     Bi B B.   . Bi:.             \n                    OM  B B   0B:B                \n                    B   B B   BB B                \n                   :B   815  UFB B                \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                             ,,...                \n                         .qBBM1SBB0MXL            \n                        rBJ     r17i8BU           \n                        B.        .  :Bvr         \n                       :B            B2BB         \n                       iB            ;BB          \n                       Mk             qB          \n                      B1Y ,     .    7B:          \n                     0M BYE    .Bq2E0B.           \n                    :B .2Xu   ,r7B:.              \n                    Ev jYYL   BB7Y                \n                    B  rS07  .BBLY                \n                   7M   1q7  iBU7Y                \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                            .                     \n                         LMOGOBBMOk:              \n                       ,BL.   .rMBPOB.            \n                       B.        .  kB:           \n                      ;B            BBB           \n                      ,B            .BB           \n                      qB             .B           \n                     7BB.S.         :O.           \n                    .B.8:B.     B55MG,            \n                    Y0 B.B    7:8q:               \n                    B.,G B   .B;Z,                \n                    B  B:B   rB:Oi                \n                   :B  12r   UB.O:                \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                            .                     \n                        .GBBOMBBkP:               \n                       LBJ     YBqNB;             \n                      vB           qBj            \n                     :B            PBB            \n                     :B             XB:           \n                     iB              B:           \n                     B:i:U         :BZ            \n                    :BjUUM     :BSqBr             \n                    ZJ5i;X    i,B:                \n                    B O,j7   .B.B                 \n                   .B EXB;   :B B                 \n                   ;B  BM    iB B                 \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                            .                     \n                        iOMBZBBB5:                \n                       X0:.   0BBONi              \n                     ,BL          .BM             \n                     BY           .BB:            \n                     Br            iXB            \n                     MB             LG            \n                    .B. Y,     i.  8B             \n                    XSB B.     YBPM;              \n                    BvP B     P:M                 \n                   :B:2 B     B.B                 \n                   ;Z:B:Z    .B B                 \n                   uL Oq8    :8 B                 \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                       ijYYFYENk.                 \n                     .BqJ. . ;BBB2:               \n                     Bj           BM              \n                    JB            BBv             \n                    Fj             rB             \n                    .B:            rB             \n                    ;X  .      U  1B.             \n                    BB.5u      BMZr.              \n                   ;0B.Mr    ,ruv                 \n                   2vO.B,    jqYS                 \n                   B.Z B.    1L:O                 \n                   B ;qB     Lj:5                 \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                       ;0NPEMBP:                  \n                     rB0;.  :BBBBv                \n                    uB           BB.              \n                   rB            BBB              \n                   LM              B              \n                   .Bqi            B              \n                    MY        YG JBU              \n                   :Br,k       BM2.               \n                   UBB7U     iiUr                 \n                   BrEUJ     qBL5                 \n                   B:Xrk     BBru                 \n                   B Bu5     BMLY                 \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                       iU2U12L,                   \n                    :BBNuirir2YOv                 \n                   YBU          EO                \n                   B:            BM               \n                  rB              B.              \n                   B7U        .  .B               \n                   jB:        BLiBL               \n                   00 B       :B7                 \n                   BBrB      7LB                  \n                   BB7M      2SB.                 \n                  ,BB7B      uuB.                 \n                  rYUrB      v5B                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                      .L5M2Li.                    \n                    EBB1::rU1BBi                  \n                  iBP         .BB                 \n                 .B:            EB                \n                 iB              B                \n                  BYr           :B                \n                   B0.       iBjB7                \n                  .B:rL       GG                  \n                  :BBBr      BjB                  \n                  :B7B.      BvB                  \n                  .BLB.      B,B                  \n                  iOBB,      Y7B                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                       ,   .                      \n                   :EBE20BBBM1:                   \n                  BB:      ..rBZ                  \n                 BU            M8                 \n                 B              B                 \n                 GY.S        v  B                 \n                  BB:        B0X;                 \n                  iM:.       rB                   \n                  1BBj      :GM:                  \n                  BBLL       BjL                  \n                  BBi7       BqJ                  \n                  BBZ7       MJX                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                   :0qMBBBBB5;                    \n                 7Yi7,    ..:ZBi                  \n                7B,           ;B:                 \n                Nq             Pq                 \n                7B  ,       :  E5                 \n                 :Mq.       .BZB                  \n                  BL:        YB                   \n                  BSB       rOB                   \n                  B0B        BqL                  \n                  BLB        BSu                  \n                  BXB        BrU                  \n",
}
